title: "Horizon Blog"
description: "News, Blog, Entertainment & More"
baseurl: "" 
url: "https://yourusername.github.io"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

paginate: 6
paginate_path: "/page:num/"
theme: null   # custom layouts use होंगे
