title: Horizon - World's Best News & Entertainment Portal
description: लेटेस्ट न्यूज, ब्लॉग, स्पोर्ट्स, एंटरटेनमेंट, ट्रेंडिंग, स्टडी, और ऑनलाइन वर्कशॉप्स का एक स्थान।
url: "http://localhost:4000"  # लोकल टेस्ट के लिए, लाइव के लिए बदलें
baseurl: ""
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
# वैकल्पिक (अगर उपयोग करना हो)
# google_analytics: UA-XXXXX-Y
# adsense_client: ca-pub-XXXX
