title: "Horizon"
description: "World's Best News & Entertainment Portal"
url: "https://<your-username>.github.io"
baseurl: ""

theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-include-cache

paginate: 6
paginate_path: "/page:num/"
