# Site Info
title: "Horizon Blog"
description: "An informational website for multitasking"
author: "Rakesh Kumar"
url: "https://horizon041.github.io"
baseurl: "/sp"  # IMPORTANT for GitHub project site

# Theme
theme: minima

# Social
twitter_username: your-horizon04
github_username: horizon041
linkedin_username: rakesh-kumar-555963d4

# Build Settings
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Sass (only if you use it)
# sass:
#   sass_dir: _sass
