# ЁЯМР Site Settings
title: "Horizon Blog"
description: "News & Updates"
url: "https://your-domain.com"   # ЁЯСЙ рдпрд╣рд╛рдБ рдЕрдкрдиреА live рд╕рд╛рдЗрдЯ рдХрд╛ URL рдбрд╛рд▓реЗрдВ
baseurl: ""                      # ЁЯСЙ рдЕрдЧрд░ subdirectory рдореЗрдВ рд╣реИ рддреЛ рдмрджрд▓реЗрдВ, рдЬреИрд╕реЗ "/blog"

# ЁЯОи Theme
theme: minima

# ЁЯУД Author Info
author:
  name: "Horizon Team"
  email: "contact@your-domain.com"

# ЁЯУС Pagination Settings
paginate: 5
paginate_path: "/page:num/"

# ЁЯФМ Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# ЁЯУ░ Excerpt Settings
excerpt_separator: "<!--more-->"   # рдкреЛрд╕реНрдЯ рдореЗрдВ рдЬрд╣рд╛рдВ рддрдХ preview рджрд┐рдЦрд╛рдирд╛ рд╣реИ

# ЁЯЫая╕П Defaults for Posts & Pages
defaults:
  - scope:
      path: ""        # рд╕рднреА рдлрд╛рдЗрд▓реЛрдВ рдкрд░ рд▓рд╛рдЧреВ
      type: "posts"
    values:
      layout: "post"
      author: "Horizon Team"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# ЁЯЧВя╕П Collections (future use)
collections:
  authors:
    output: true

# тЬЕ Markdown & Syntax Highlighter
markdown: kramdown
highlighter: rouge

# тЬЕ Permalinks
permalink: /:categories/:year/:month/:day/:title/
