# Jekyll configuration file for a GitHub Pages site

title: "Your Site Title"
description: "A short description of your site"
author: "Your Name"
email: "your-email@example.com"
url: "https://horizon041.github.io"
baseurl: "" # Leave empty for GitHub Pages user/organization site, use "/repo-name" for project sites

# Theme (choose one, e.g., minima, cayman, slate, etc.)
theme: minima

# Social Links (optional)
twitter_username: your-twitter
github_username: horizon041
linkedin_username: your-linkedin

# Build settings
markdown: kramdown
permalink: pretty

# Plugins (optional, for advanced features)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files/folders from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults (optional)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# Collections (optional)
# collections:
#   my_collection:
#     output: true

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Pagination (optional)
# paginate: 5
# paginate_path: "/page:num/"

# Custom Variables (optional)
# custom_var: "value"
backend:
  name: github
  repo: your-username/your-repo-name # अपने GitHub रेपो का नाम डालें
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: "blog"
    label: "Blog Posts" # डैशबोर्ड में दिखने वाला नाम
    folder: "src/content/blog" # ब्लॉग पोस्ट्स की Markdown फाइल्स कहाँ स्टोर होंगी
    create: true # नई पोस्ट बनाने की अनुमति
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # फाइल नेम फॉर्मेट
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
