# Site settings
title: "Horizon"
description: "Horizon - World’s Best News & Entertainment Portal"
lang: "hi"
timezone: "Asia/Kolkata"
url: ""        # GitHub Pages के लिए खाली
baseurl: "/horizon04" # Repo name adjust karein

# Author info
author:
  name: "Horizon Team"
  email: "horizon-team@example.com"

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
sass:
  sass_dir: assets/css
  style: compressed

# Plugins
plugins:
  - jekyll-remote-theme  # Minima remote theme ke liye
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate  # Only if using pagination
  - jekyll-archives
  - jekyll-include-cache

# Pagination (optional, remove if not needed)
paginate: 6
paginate_path: "/page:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
    - year
    - month
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    category: '/category/:name/'

# Exclude/Include
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
include:
  - _pages

# Permalink
permalink: /:categories/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Horizon Team"
      lang: "hi"
      seo:
        type: "article"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      lang: "hi"
      seo:
        type: "website"
