title: "Horizon"
description: "Horizon - World’s Best News & Entertainment Portal"
lang: "hi"
timezone: "Asia/Kolkata"
url: "https://horizon041.github.io"  # Your GitHub Pages URL
baseurl: "/horizon04"

author:
  name: "Horizon Team"
  email: "horizon-team@example.com"

markdown: kramdown
remote_theme: jekyll/minima
sass:
  sass_dir: assets/css
  style: compressed

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

paginate: 6
paginate_path: "/page:num/"

jekyll-archives:
  enabled:
    - categories
    - year
    - month
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    category: '/category/:name/'

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
include:
  - _pages

permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Horizon Team"
      lang: "hi"
      seo:
        type: "article"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      lang: "hi"
      seo:
        type: "website"
