title: "Horizon"
description: "World's Best News & Entertainment Portal"
baseurl: "" 
url: "https://horizon041.github.io" # अपने GitHub Pages URL डालना
theme: minima

# Optional settings
google_analytics: ""   # GA ID डाल सकते हो
adsense_client: ""     # Adsense client ID डाल सकते हो
