# Jekyll configuration file for a GitHub Pages site

title: "Horizon Blog"
description: "a informational website for multitasking"
author: "Rakesh Kumar"
url: "https://horizon041.github.io/.github.io/#"  # अपनी साइट का URL
baseurl: ""  # Leave empty for GitHub Pages user/organization site, use "/repo-name" for project sites

# Theme (choose one, e.g., minima, cayman, slate, etc.)
theme: minima

# Social Links (optional)
twitter_username: your-horizon04
github_username: horizon041
linkedin_username: rakesh-kumar-555963d4

# Build settings
permalink: pretty

# Plugins (optional, for advanced features)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files/folders from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults (optional)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Collections (optional)
collections:
  posts:
    output: true
    permalink: /:categories/:title/
  my_collection:
    output: true  # अगर आप my_collection का उपयोग करना चाहते हैं

# Analytics (optional)
# google_analytics: UA-XXXXXX-X

# Pagination (optional)
paginate: 5
paginate_path: "/page:num/"

# Custom Variables (optional)
# custom_var: "value"
