[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.1.2"  # या जो भी आपकी Gemfile में हो
  BUNDLER_VERSION = "2.4.22"  # अगर ज़रूरत हो

[[redirects]]
  from = "/admin"
  to = "/static/admin/index.html"
  status = 200
