[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.0"          # Ruby का latest stable use करें
  BUNDLER_VERSION = "2.4.22"

[[redirects]]
  from = "/admin"
  to = "/static/admin/index.html"
  status = 200
