[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.0"  # या जो भी आपकी Gemfile में हो

[[redirects]]
  from = "/admin"
  to = "/static/admin/index.html"
  status = 200
